### PR TITLE
[pt-PT] Added compound words to AO45 and AO90

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya, @p-goulart 

So, this was it?

I thought I would have to search for the compounds files, but they were in a folder right in front of me.

😛 😛 😛 😛 😛 😛

### CODE REVIEW

**Comment by marcoagpinto** [comment]
Heya, @p-goulart 

LanguageTool entered feature freeze today, could you approve these changes before the official release?

Thanks!

**Review by p-goulart — APPROVED** [review]

**Comment by marcoagpinto** [comment]
@p-goulart 

Thank you for approving, but you must merge it because I have no access to that command in this repository.

I was just waiting for this pull request to be approved so that I could start working slowly in adding words and postags.

I will be adding words and postags slowly and updating the files so that in a next dictionary/postag release, the WIP can be merged as a whole.

Thanks!

**Comment by p-goulart** [comment]
@marcoagpinto, I have granted you rights to bypass pull request approvals. I'm keeping in place the requirement that tests pass, however.

Please make sure the pipeline is successful so we know for a fact the changes are not detrimental. In this case, if you read the message, it simply means pointing the GitHub Actions configuration to a valid branch by changing the value of the `LT_BRANCH` variable. If you don't have a feature branch on the main LT repo yet, simply `master` should do the trick.

**Comment by marcoagpinto** [comment]
@p-goulart 

I still don't have the knowledge on how to fix this pull request.

The best way of fixing it is by closing it, then I will create another checkout and will start adding the words/postags missing including the ones here.

Thanks!

❤️ ❤️ ❤️ ❤️ ❤️

**Comment by marcoagpinto** [comment]
@p-goulart 

Help!

My clone of the repository... I only see "main" in the branch.

Should I in Tortoise Git press to commit to "main"?

Will this create a pull request or immediately merge the commit?

I need to be sure so that I don't screw up.

Thanks!

**Comment by p-goulart** [comment]
> I still don't have the knowledge on how to fix this pull request.

I told you how here:

> pointing the GitHub Actions configuration to a valid branch by changing the value of the LT_BRANCH variable. If you don't have a feature branch on the main LT repo yet, simply master should do the trick.

To spell it out:

- go to `.github/workflows/build.yml`;
- on line 34, you should see:

```yml
LT_BRANCH: "pt/dict/v1.2.0"
```

- this branch is outdated (it was for a specific release, as per the README);
- change that to `master`.

> The best way of fixing it is by closing it

This is not true. You can open and close this PR as many times as you want, and so long as the GHA config points to a non-existing LT branch, the tests will not magically fix themselves...

> Should I in Tortoise Git press to commit to "main"?

Please do not commit straight to main. See the point below.

---

Alternatively, add your words to the `spelling` and `added` files in the LT repo and request @susanaboatto's approval. It'll work as a hotfix. When the time comes to release a new dictionary, I can move the words here myself, prepare the release, make sure all tests pass, and trigger the deployment.

That way, you'll get to suggest your improvements without having to contribute to this repo.

**Comment by p-goulart** [comment]
I've rebased this on the fixed `main` branch with the latest LT snapshot and the correct LT upstream `master` branch.

**Pull request merged**
