### PR TITLE
[pt-PT] Improved both .AFF files for AO45 and AO90

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya, @susanaboatto and @p-goulart 

Like I said yesterday, I will do this task bit by bit to make sure I won't screw up.

So, here is an improvement for verb forms of the kind:
```
ama-a
ama-as
ama-lhe
ama-lhes
ama-me
ama-nos
ama-o
ama-os
ama-se
ama-se-lhe
ama-se-lhes
ama-te
ama-vos
```

NEW WORDS (AO45):
[3.PTPT_45_new_verbs.txt](https://github.com/languagetool-org/portuguese-pos-dict/files/14093809/3.PTPT_45_new_verbs.txt)

NEW WORDS (AO90):
[6.PTPT_90_new_verbs.txt](https://github.com/languagetool-org/portuguese-pos-dict/files/14093810/6.PTPT_90_new_verbs.txt)

PS→ Moments ago I forgot to create a Pull Request, so in the Git software I selected to amend it and repulled it.

### CODE REVIEW

**Comment by p-goulart** [comment]
@marcoagpinto , for the time being, can you work off `tagging/clitics` instead of `main`? That's the branch where we're adding the new tokenisation logic. I'll change the base of this PR.

**Comment by marcoagpinto** [comment]
@p-goulart 

Ahhhh… Heya,

How do I work on `/clitics`?

I have the repository in a folder and I search for 45.aff, and it shows a folder from where I get/commit the .AFFs.

**Comment by p-goulart** [comment]
Instead of checking out the `main` branch, checkout `tagging/clitics`. When creating your new branch, make sure it's based on `tagging/clitics`.

**Comment by marcoagpinto** [comment]
> Instead of checking out the `main` branch, checkout `tagging/clitics`. When creating your new branch, make sure it's based on `tagging/clitics`.

Ahhhhh… thanks!

I will try to check out that instead of the main.

**Comment by marcoagpinto** [comment]
@p-goulart @susanaboatto @jaumeortola 

HELP!!!!!

Screenshot 2024-01-30 183845

**Comment by susanaboatto** [comment]
@marcoagpinto you don't need to clone it again if you already have the `portuguese-pos-dict` repo available. All you need to do is look for the `tagging/clitics` branch under the repo's branches, as you do with any of your other branches. Try updating the project first if you can't find it 😉  
image

**Comment by marcoagpinto** [comment]
Ahhhh… thanks, @susanaboatto , I will try tonight.

My idea of copying rules from the pt-BR into the pt-PT worked fine, just like I expected.

All I have to do is to change the flags names and numbers.

**Pull request merged**
