### PR TITLE
[pt-PT] Improved AFFs of AO45 and AO90

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya, @susanaboatto and @p-goulart 

I have improved the AFFs.

It adds near 100 conjugations, not much, but at least they are all valid.

```
combatê-la-á
combatê-la-ão
combatê-la-ás
combatê-la-ia
combatê-la-iam
combatê-la-íamos
combatê-la-ias
combatê-las-á
combatê-las-ão
combatê-las-ás
combatê-las-ei
combatê-las-eis
combatê-las-ia
combatê-las-iam
combatê-las-íamos
combatê-las-ias
combatê-los-á
combatê-los-ão
combatê-los-ei
combatê-los-eis
combatê-los-ia
combatê-los-iam
combatê-los-íamos
combatê-los-ias
debatê-la-á
debatê-la-ão
debatê-la-ás
debatê-la-ia
debatê-la-iam
debatê-la-íamos
debatê-la-ias
debatê-las-á
debatê-las-ão
debatê-las-ás
debatê-las-ei
debatê-las-eis
debatê-las-ia
debatê-las-iam
debatê-las-íamos
debatê-las-ias
debatê-los-á
debatê-los-ão
debatê-los-ei
debatê-los-eis
debatê-los-ia
debatê-los-iam
debatê-los-íamos
debatê-los-ias
esbatê-la-á
esbatê-la-ão
esbatê-la-ás
esbatê-la-ia
esbatê-la-iam
esbatê-la-íamos
esbatê-la-ias
esbatê-las-á
esbatê-las-ão
esbatê-las-ás
esbatê-las-ei
esbatê-las-eis
esbatê-las-ia
esbatê-las-iam
esbatê-las-íamos
esbatê-las-ias
esbatê-los-á
esbatê-los-ão
esbatê-los-ei
esbatê-los-eis
esbatê-los-ia
esbatê-los-iam
esbatê-los-íamos
esbatê-los-ias
rebatê-la-á
rebatê-la-ão
rebatê-la-ás
rebatê-la-ia
rebatê-la-iam
rebatê-la-íamos
rebatê-la-ias
rebatê-las-á
rebatê-las-ão
rebatê-las-ás
rebatê-las-ei
rebatê-las-eis
rebatê-las-ia
rebatê-las-iam
rebatê-las-íamos
rebatê-las-ias
rebatê-los-á
rebatê-los-ão
rebatê-los-ei
rebatê-los-eis
rebatê-los-ia
rebatê-los-iam
rebatê-los-íamos
rebatê-los-ias
```

Missing in pt-BR with ChatGPT help:
```
Estas formas verbais existem em português de Portugal?: "combatê-la-ão","combatê-la-íamos","combatê-la-ias","combatê-las-ão","combatê-las-eis","combatê-las-íamos","combatê-las-ias","combatê-los-ão","combatê-los-eis","combatê-los-íamos","combatê-los-ias"

Sim, as formas verbais que você apresentou existem em português de Portugal. Elas correspondem a conjugações do verbo "combater" em diferentes tempos verbais e modos, utilizando pronomes átonos para indicar o objeto direto da ação ("o", "a", "os", "as").
=========

Estas formas verbais existem em português de Portugal?: "debatê-la-ão","debatê-la-íamos","debatê-la-ias","debatê-las-ão","debatê-las-eis","debatê-las-íamos","debatê-las-ias","debatê-los-ão","debatê-los-eis","debatê-los-íamos","debatê-los-ias"

Sim, todas essas formas verbais são corretas em português de Portugal. Elas correspondem a conjugações do verbo "debaater" em diferentes tempos verbais e modos, usando pronomes átonos para indicar o objeto direto da ação ("o", "a", "os", "as").

=========

Estas formas verbais existem em português de Portugal?: "rebatê-la-ão","rebatê-la-íamos","rebatê-la-ias","rebatê-las-ão","rebatê-las-eis","rebatê-las-íamos","rebatê-las-ias","rebatê-los-ão","rebatê-los-eis","rebatê-los-íamos","rebatê-los-ias"

Sim, todas essas formas verbais são corretas em português de Portugal. Elas correspondem a conjugações do verbo "rebatê-la" e "rebatê-las" em diferentes tempos verbais e modos, utilizando pronomes átonos para indicar o objeto direto da ação ("o", "a", "os", "as").
```

### CODE REVIEW

**Review by p-goulart — APPROVED** [review]

**Comment by marcoagpinto** [comment]
@p-goulart 

The “Squash and merge” is disabled here again, maybe because it failed the tests, or I don't have permission to press it.

Please press it for me if you can.

Thanks!

**Comment by marcoagpinto** [comment]
Thanks!

**Comment by p-goulart** [comment]
@marcoagpinto we need to make some changes to the affix files in both languages ourselves – we'll let you know once we're done, but for now it's probably safer if you leave them alone for a little while to avoid conflicts.

**Comment by marcoagpinto** [comment]
@p-goulart 

Heya, thanks for letting me know.

Anyway, I have a meeting on 16-MAR with the Professor and I couldn't do much with the affixes before it.

Thanks!

**Pull request merged**
