### PR TITLE
[pt-PT] Improved .AFF files for both AO45 and AO90

### PR DESCRIPTION
**Pull request by marcoagpinto**
Heya, @susanaboatto and @p-goulart 

I hope to have committed to the right branch this time.

This commit adds verbal forms such as:
```
ame-a
ame-as
ame-lhe
ame-lhes
ame-me
ame-nos
ame-o
ame-os
ame-se
ame-se-lhe
ame-se-lhes
ame-te
ame-vos
```

But in AO90 it added 58465 words, could you give a quick look to check if everything is fine? It is crazy to have so many new words since the dictionaries are maintained by Minho University for decades and from one moment to the other it raises 58 thousand words?

AO45:
[3.PTPT_45_new_verbs.txt](https://github.com/languagetool-org/portuguese-pos-dict/files/14134967/3.PTPT_45_new_verbs.txt)

AO90:
[6.PTPT_90_new_verbs.txt](https://github.com/languagetool-org/portuguese-pos-dict/files/14134974/6.PTPT_90_new_verbs.txt)

😛 😛 😛 😛 😛 😛 😛 😛 😛 

Thanks!

### CODE REVIEW

**Comment by marcoagpinto** [comment]
Ahhhh… like the last one, these rules were copied from the pt-BR dictionary, so they work exactly like they do there.

**Comment by p-goulart** [comment]
The number rings true to me. Since we are adding pronouns **in combination with** endings, the increase is exponential. To me his looks okay.

**Review by p-goulart — APPROVED** [review]
Sorry, was certain that other comment came with an approving review. Anyway, looks good.

**Comment by marcoagpinto** [comment]
@p-goulart 

Thanks!

I have now merged it, but notice that “all checks failed”.

**Comment by p-goulart** [comment]
These tests will be failing for a while on this branch, until we fix all the issues with the XML rules as well as pt-PT tagging.

**Pull request merged**
